<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIye7XK0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIye7XK0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIye7XK0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIye7XK0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIye7XK0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Iye7XK0',
    'container.build_id' => '55a95cfd',
    'container.build_time' => 1617135035,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIye7XK0');
